import AllProvider from '@/providers/Auth-&-TRPCClient-Provider'
import '../app/assets/globals.css'
import type { Metadata } from 'next'
import { Toaster } from "@/components/ui/toaster"
import Navbar from '@/components/Navbar'
import { pageProps } from '../../types/all-required-types'

export const metadata: Metadata = {
	title: 'Clickk® | Home',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

	return (
		<html lang="en">
			<AllProvider>
				<body>
					{children}
					<Toaster />
				</body>
			</AllProvider>
		</html>
	)
}