import AuthenticationProvider from '@/providers/Auth-&-TRPCClient-Provider'
import '../app/assets/globals.css'
import type { Metadata } from 'next'
import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
	title: 'Clickk® | Home',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link rel="shortcut icon" href="public/img/logo.ico" />
				<link rel='icon' type="image/icon" sizes="32x32" href='public/img/logo.ico' />
			</head>
			<AuthenticationProvider>
				<body>
					{children}
					<Toaster />
				</body>
			</AuthenticationProvider>
		</html>
	)
}