import '@/app/assets/globals.css'
import type { Metadata } from 'next'
import DashboardNavbar from '@/components/dashboard/DashboardNavbar'
import { Suspense } from "react";
import Loading from '../loading';

export const metadata: Metadata = {
    title: 'Clickk™ | Dashboard 📫',
    description: 'Generated by create next app',
}

export default function DashBoardLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className='relative'>
            <DashboardNavbar/>
            <Suspense fallback={<Loading type='big' message='Loading...'/>}>
                {children}
            </Suspense>
        </main>
    )
}