import '@/app/assets/globals.css'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import { Suspense } from "react";
import Loading from '@/app/loading';
import { GetUserDetails } from '../../lib/dataHelpers';
import { redirect } from 'next/navigation';
import { DashboardWrapper } from '@/components/dashboard/DashboardWrapper';

export const metadata: Metadata = {
    title: 'Clickk™ | Dashboard 📫',
    description: 'Generated by create next app',
}

export default async function DashBoardLayout({ children }: { children: React.ReactNode }) {

    const userData = await GetUserDetails()
    if(userData.length === 0) redirect("/api/auth/signin")

    return (
        <main className='relative'>
            <Suspense fallback={<Loading type='big' message='LOADING'/>}>
                <DashboardWrapper data={userData}>
                    <Navbar toBeUsedAt='dashboard'/>
                    {children}
                </DashboardWrapper>
            </Suspense>
        </main>
    )
}